# Generated by Django 3.2.7 on 2022-05-10 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0002_file_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='动态标题')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '发布'), ('abandoned', '废弃')], max_length=20, verbose_name='状态')),
                ('content', models.TextField(verbose_name='动态内容')),
                ('medias', models.ManyToManyField(to='media.File', verbose_name='图片和视频')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
                'db_table': 'issues',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.issues', verbose_name='对应动态')),
                ('medias', models.ManyToManyField(to='media.File', verbose_name='图片和视频')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='回复者')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='re_reply', to='square.reply', verbose_name='对应回复')),
            ],
            options={
                'verbose_name': '动态回复',
                'verbose_name_plural': '动态回复',
                'db_table': 'replies',
            },
        ),
        migrations.CreateModel(
            name='ThumbsUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dy_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='square.issues', verbose_name='对应动态')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='square.reply', verbose_name='对应回复')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞者')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'thumbs_up',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.issues', verbose_name='对应动态')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'collection',
            },
        ),
    ]
