# Generated by Django 3.2.7 on 2022-05-18 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('square', '0001_initial'),
        ('media', '0002_file_uploader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbsup',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞者'),
        ),
        migrations.AddField(
            model_name='thumbsup',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='square.reply', verbose_name='对应回复'),
        ),
        migrations.AddField(
            model_name='reply',
            name='issues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.issues', verbose_name='对应动态'),
        ),
        migrations.AddField(
            model_name='reply',
            name='medias',
            field=models.ManyToManyField(to='media.File', verbose_name='图片和视频'),
        ),
        migrations.AddField(
            model_name='reply',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='回复者'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='re_reply', to='square.reply', verbose_name='对应回复'),
        ),
        migrations.AddField(
            model_name='issues',
            name='medias',
            field=models.ManyToManyField(to='media.File', verbose_name='图片和视频'),
        ),
        migrations.AddField(
            model_name='issues',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='collection',
            name='issues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.issues', verbose_name='对应动态'),
        ),
        migrations.AddField(
            model_name='collection',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
    ]
