# Generated by Django 3.2.7 on 2022-05-29 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bussiness', '0001_initial'),
        ('media', '0003_auto_20220521_1115'),
        ('square', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='bussiness.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='medias',
            field=models.ManyToManyField(blank=True, null=True, to='media.File', verbose_name='图片和视频'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='origin_issues', to='square.issues', verbose_name='原动态'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='bussiness.Tag', verbose_name='标签'),
        ),
    ]
