# Generated by Django 3.2.7 on 2022-05-13 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('square', '0002_auto_20220511_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.AlterField(
            model_name='issues',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
    ]
