# Generated by Django 3.2.7 on 2022-05-24 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('square', '0003_auto_20220524_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.issues', verbose_name='对应动态')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='分享者')),
            ],
            options={
                'verbose_name': '分享',
                'verbose_name_plural': '分享',
                'db_table': 'share',
            },
        ),
    ]
