# Generated by Django 3.2.7 on 2022-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('square', '0003_auto_20220531_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='发布时ip地址'),
        ),
    ]
