# Generated by Django 3.2.7 on 2022-05-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0003_auto_20220513_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbsup',
            old_name='dy_info',
            new_name='issues',
        ),
    ]
