# Generated by Django 3.2.7 on 2022-06-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('square', '0005_issues_is_vedio_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='评论时ip地址'),
        ),
    ]
