# Generated by Django 3.2.7 on 2022-06-12 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('square', '0008_issues_video_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='version',
        ),
    ]
