# Generated by Django 3.2.7 on 2022-06-17 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('square', '0009_auto_20220612_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
