# Generated by Django 3.2.7 on 2022-10-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0010_delete_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='动态标题'),
        ),
    ]
