# Generated by Django 3.2.7 on 2022-08-06 18:34

import apps.interfaces.can_collection
import apps.interfaces.can_share
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0006_alter_file_options'),
        ('business', '0006_tasklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='数据创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='数据失效时间')),
                ('name', models.CharField(default='佚名', max_length=255, verbose_name='作者姓名')),
                ('birthday', models.CharField(blank=True, max_length=50, null=True, verbose_name='出身年月')),
                ('introduce', models.TextField(default='', verbose_name='介绍')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='联系地址')),
                ('contact', models.CharField(blank=True, help_text='联系电话或手机号码', max_length=50, null=True, verbose_name='联系方式')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '作者信息',
                'verbose_name_plural': '作者信息',
                'db_table': 'author',
            },
            bases=(models.Model, apps.interfaces.can_share.CanShare, apps.interfaces.can_collection.CanCollection),
            managers=[
                ('logic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='数据创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='数据失效时间')),
                ('title', models.CharField(default='无题', max_length=255, verbose_name='艺术品标题')),
                ('creative_work_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='创作时间')),
                ('is_original', models.BooleanField(default=True, verbose_name='是否原创')),
                ('is_uploader_has', models.BooleanField(default=True, verbose_name='是否上传者拥有')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artwork.author', verbose_name='作家')),
                ('category', models.ManyToManyField(to='business.Category', verbose_name='分类')),
                ('medias', models.ManyToManyField(blank=True, to='media.File', verbose_name='图片或视频')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_uploader', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.interfaces.can_share.CanShare, apps.interfaces.can_collection.CanCollection),
            managers=[
                ('logic_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
