# Generated by Django 3.2.7 on 2022-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_category_parent_category'),
        ('artwork', '0002_auto_20220815_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='last_height',
            field=models.FloatField(default=0, help_text='单位厘米(cm)', verbose_name='最高处高度'),
        ),
        migrations.AddField(
            model_name='art',
            name='last_length',
            field=models.FloatField(default=0, help_text='单位厘米(cm)', verbose_name='最长处长度'),
        ),
        migrations.AddField(
            model_name='art',
            name='last_width',
            field=models.FloatField(default=0, help_text='单位厘米(cm)', verbose_name='最宽处宽度'),
        ),
        migrations.AddField(
            model_name='art',
            name='tags',
            field=models.ManyToManyField(to='business.Tag', verbose_name='标签'),
        ),
    ]
