---
kind: pipeline
type: docker
name: deer-block-build

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: 101.35.246.34/deer_block/deer-block-server
      registry: 101.35.246.34
      insecure: true
      use_cache: true
      username: xiaozuhui
      password: 1qazXDR%
      tags: ${DRONE_TAG=latest}
      when:
        event: [ push, tag, deployment ]
        branch: master

---
kind: pipeline
type: docker
name: deer-block-deploy

depends_on: # 依赖build管道
  - deer-block-build

clone:
  disable: true # 禁用拉取

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 101.35.246.34
      user: ubuntu
      password: Shiki921128?
      port: 22
      command_timeout: 10m
      script:
        - echo ====开始部署=======
        - docker pull 101.35.246.34/deer_block/deer-block-server:latest
        - docker-compose -f /etc/docker-compose/deer_block_server/docker-compose.yml up -d
        - docker rmi $(docker images | grep deploy-web-demo | grep none | awk  '{print $3}')
        - echo ====部署成功=======