---
kind: pipeline
type: docker
name: 镜像打包

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: deer_block/deer-block-server
      registry: 
      insecure: true
      use_cache: true
      username: 
      password: 
      tags: ${DRONE_TAG=latest}
      when:
        event: [ push, tag, deployment ]
        branch: master

trigger:
  branch:
    - master
  event:
    - push
    - tag
    - deployment
    - pull_request

---
kind: pipeline
type: docker
name: 镜像部署

depends_on: # 依赖build管道
  - 镜像打包

clone:
  disable: true # 禁用拉取

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
      user:
      password:
      port: 22
      command_timeout: 10m
      script:
        - echo ====开始部署=======
        - docker pull deer_block/deer-block-server:latest
        - docker-compose -f /etc/docker-compose/deer_block_server/docker-compose.yml up -d
        - echo ====部署成功=======

trigger:
  branch:
    - master
  event:
    - push
    - tag
    - deployment
    - pull_request