---
kind: pipeline
type: docker
name: deer-block-build

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: 101.35.246.34/deer_block/deer-block-server
      registry: 101.35.246.34
      insecure: true
      use_cache: true
      username:
        from_secret: xiaozuhui
      password:
        from_secret: 1qazXDR%
      tags: ${DRONE_TAG=latest}
      when:
        event: [ push, tag, deployment ]
        branch: master
