version: '3'

services:
  db:
    image: postgres:13
    ports:
      - "15432:5432"
    volumes:
      - /var/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=deer_block
    container_name: deer_block_postgres
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "16379:6379"
    container_name: deer_block_redis
    restart: always
  deerblock:
    image: deer_block/deer-block-server:v1
    ports:
      - "18080:8088"
    # 替换成线上生产
    volumes:
      - /var/log/deer_block_server:/opt/deer_block/logs/
    environment:
      - POSTGRES_NAME=deer_block
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      # OSS 阿里云
      - OSS_ACCESS_KEY_ID=LTAI5tEqusWURSPxDZAWnhNZ
      - OSS_ACCESS_KEY_SECRET=HRxY0tiNUCuQ553ku6Mxsma2ncdafn
      - OSS_ENDPOINT=oss-cn-shanghai.aliyuncs.com
      - OSS_BUCKET_NAME=papaw
      # 短信发送
      - SEND_MESSAGE_ACCESS_KEY=LTAI5tKqWQhoEfRhyJKc15yW
      - SEND_MESSAGE_ACCESS_SECRET=FGhlSPqkSE7qmZksPUYya762j2AdaR
      - SEND_MSG_MODE=aliyun
      - SIGN_NAME=阿里云短信测试
      - TEMPLATE_CODE=SMS_154950909
    container_name: deer_block_server
    command: /bin/bash -c "python3 /opt/deer_block/manage.py makemigrations && python3 /opt/deer_block/manage.py migrate && gunicorn -c /opt/deer_block/gunicorn.conf.py deer_block.wsgi:application"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    restart: always
