version: '3'

services:
  db:
    image: postgres:13
    ports:
      - "15432:5432"
    volumes:
      - /var/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=deer_block
    container_name: deer_block_postgres
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "16379:6379"
    container_name: deer_block_redis
    restart: always
  minio:
    image: quay.io/minio/minio:RELEASE.2022-05-08T23-50-31Z
    command: server --address ":9000" --console-address ":9001" /data
    container_name: db_minio_server
    ports:
      - "19090:9000"
      - "19091:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 1qazXDR%?
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - /var/data/minio/data:/data #映射当前目录下的data目录至容器内/data目录
      - /var/data/minio/config:/root/.minio/ #映射配置目录
    privileged: true
    restart: always
