version: '3.7'

services:
  db:
    image: postgres:13
    ports:
      - "15432:5432"
    volumes:
      - /var/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=deer_block
    container_name: deer_block_postgres
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "16379:6379"
    container_name: deer_block_redis
    restart: always
  minio:
    image: quay.io/minio/minio:RELEASE.2022-05-08T23-50-31Z
    command: server --address ":9000" --console-address ":9001" /data
    container_name: db_minio_server
    expose:
      - "19090:9000"
      - "19091:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 1qazXDR%?
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
        - /docker/minio/data:/data               #映射当前目录下的data目录至容器内/data目录
        - /docker/minio/config:/root/.minio/     #映射配置目录
    privileged: true
    restart: always
  deerblock:
    image: 101.35.246.34/deer_block/deer-block-server:latest
    ports:
      - "18080:8088"
    # 替换成线上生产
    volumes:
      - /var/log/deer_block_server:/opt/deer_block/logs/
    environment:
      # 数据库链接信息
      - POSTGRES_NAME=deer_block
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      # 缓存配置-默认redis
      - CACHE_LOCATION_IP=redis
      - CACHE_LOCATION_PORT=6379
      # OSS 阿里云
      - OSS_ACCESS_KEY_ID=LTAI5tEqusWURSPxDZAWnhNZ
      - OSS_ACCESS_KEY_SECRET=HRxY0tiNUCuQ553ku6Mxsma2ncdafn
      - OSS_ENDPOINT=oss-cn-shanghai.aliyuncs.com
      - OSS_BUCKET_NAME=papaw
      # 短信发送
      - SEND_MESSAGE_ACCESS_KEY=LTAI5tKqWQhoEfRhyJKc15yW
      - SEND_MESSAGE_ACCESS_SECRET=FGhlSPqkSE7qmZksPUYya762j2AdaR
      - SEND_MSG_MODE=aliyun
      - SIGN_NAME=阿里云短信测试
      - TEMPLATE_CODE=SMS_154950909
      # minio 
      # TODO 上线的时候需要修改
      - MINIO_IP=101.35.246.34
      - MINIO_PORT=19090
      - MINIO_SET_IP=minio
      - MINIO_SET_PORT=9000
      - MINIO_STORAGE_ACCESS_KEY=root
      - MINIO_STORAGE_SECRET_KEY=1qazXDR%?
      - MINIO_STORAGE_USE_HTTPS=False
      - MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET=True
    container_name: deer_block_server
    command: /bin/bash -c "python3 /opt/deer_block/manage.py makemigrations && python3 /opt/deer_block/manage.py migrate && gunicorn -c /opt/deer_block/gunicorn.conf.py deer_block.wsgi:application"
    links:
      - db
      - redis
      - minio
    depends_on:
      - db
      - redis
      - minio
    restart: always
