# Generated by Django 3.2.7 on 2022-06-17 09:22

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import apps.interfaces.can_comment
import apps.interfaces.can_thumbup


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0006_alter_file_options'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('business', '0003_share_share_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collecter',
        ),
        migrations.RemoveField(
            model_name='share',
            name='sharer',
        ),
        migrations.RemoveField(
            model_name='thumbup',
            name='tper',
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collector',
                                    to='users.user', verbose_name='收藏者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sharer',
                                    to='users.user', verbose_name='分享者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thumbup',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tper',
                                    to='users.user', verbose_name='点赞者'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='数据创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='数据失效时间')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True, verbose_name='评论内容')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='评论ip地址')),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('medias', models.ManyToManyField(blank=True, to='media.File', verbose_name='图片和视频')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter',
                                           to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
            bases=(models.Model, apps.interfaces.can_thumbup.CanThumbUp, apps.interfaces.can_comment.CanComment),
            managers=[
                ('logic_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
