# Generated by Django 3.2.7 on 2022-07-28 22:30

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0004_auto_20220617_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='数据创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='数据失效时间')),
                ('source_type',
                 models.CharField(choices=[('issues', '动态消息'), ('user', '用户私信'), ('shop', '商城消息'), ('system', '系统消息')],
                                  max_length=10, verbose_name='消息源')),
                ('message_content', models.JSONField(blank=True, null=True, verbose_name='消息内容')),
                ('has_consumed', models.BooleanField(default=False, verbose_name='是否已被消费')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'message',
                'managed': False,
            },
            managers=[
                ('logic_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
