# Generated by Django 3.2.7 on 2022-08-06 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='数据创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='数据失效时间')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.UUIDField(unique=True)),
                ('from_model', models.CharField(max_length=50, verbose_name='对应模型')),
                ('celery_function', models.CharField(max_length=255, verbose_name='方法名称')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('final_status', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='最终状态')),
                ('is_success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('args', models.JSONField(blank=True, null=True, verbose_name='传递参数')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='返回值')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='启动任务时的用户')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'db_table': 'task_log',
            },
            managers=[
                ('logic_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
