# Generated by Django 3.2.7 on 2022-08-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_tasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='backup',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='share',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='分享信息'),
        ),
        migrations.AddField(
            model_name='tag',
            name='backup',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=100, unique=True, verbose_name='分类'),
        ),
    ]
