# Generated by Django 3.2.7 on 2022-08-19 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='first_class_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_comment', to='business.comment', verbose_name='第一级评论'),
        ),
    ]
