# Generated by Django 3.2.7 on 2022-04-17 17:53

import apps.custom_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='', max_length=120, verbose_name='昵称')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('sex', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=20, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('avatar', apps.custom_models.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_avatar', to='media.file')),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
