# Generated by Django 3.2.7 on 2022-05-10 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='user_follow', to=settings.AUTH_USER_MODEL, verbose_name='关注'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='user_followed', to=settings.AUTH_USER_MODEL, verbose_name='被关注'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付功能',
                'verbose_name_plural': '支付功能',
                'db_table': 'user_payment',
            },
        ),
    ]
