# Generated by Django 3.2.7 on 2022-05-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220511_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='userpayment',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='delete_at',
            new_name='deleted_at',
        ),
    ]
