# Generated by Django 3.2.7 on 2022-09-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_level_next_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelgroup',
            name='levels',
            field=models.ManyToManyField(to='users.Level', verbose_name='等级'),
        ),
    ]
