# Generated by Django 3.2.7 on 2022-09-04 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_upgrademethod_upgrade_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrademethod',
            name='code',
        ),
    ]
