# Generated by Django 3.2.7 on 2022-10-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_upgrademethod_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_level',
            field=models.IntegerField(default=0, verbose_name='用户等级'),
        ),
    ]
