class CanThumbUp:
    """能够被点赞的模型interface
    """

    def create_thumbs_up(self, user): ...

    def delete_thumbs_up(self, user): ...

    def get_thumb_up(self, user): ...

    def get_thumb_ups(self): ...
