# Generated by Django 3.2.7 on 2022-05-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bussiness', '0002_share_share_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='share_type',
            field=models.CharField(default='', max_length=20, verbose_name='分享类型'),
        ),
    ]
