# Generated by Django 3.2.7 on 2022-05-18 10:01

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models

import apps.media.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_list', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(),
                                                                        default=apps.media.models.default_array,
                                                                        size=9)),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '基础文件管理',
                'verbose_name_plural': '基础文件管理',
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('filename', models.CharField(default='', max_length=50, verbose_name='文件名')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
                ('sequence', models.IntegerField(default=0, verbose_name='顺序')),
                ('is_private', models.BooleanField(default=False, verbose_name='是否私有')),
            ],
        ),
    ]
