# Generated by Django 3.2.7 on 2022-05-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='文件标题')),
                ('file_type', models.CharField(choices=[('', '无类型'), ('video', '视频'), ('image', '图像'), ('file', '文件')], default='', max_length=50, verbose_name='文件类型')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
                ('sequence', models.IntegerField(default=0, verbose_name='顺序')),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_private', models.BooleanField(default=False, verbose_name='是否私有')),
            ],
            options={
                'verbose_name': '基础文件管理',
                'verbose_name_plural': '基础文件管理',
                'db_table': 'file',
            },
        ),
    ]
