# Generated by Django 3.2.7 on 2022-04-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
