# Generated by Django 3.2.7 on 2022-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('media', '0003_auto_20220521_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='file_extension',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='文件后缀'),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='mime_type',
            field=models.CharField(blank=True, max_length=215, null=True, verbose_name='内部类型'),
        ),
    ]
