# Generated by Django 3.2.7 on 2022-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20220605_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='file_type',
            field=models.CharField(choices=[('', '无类型'), ('video', '视频'), ('image', '图像'), ('audio', '音频'), ('other', '其他')], default='', max_length=20, verbose_name='文件类型'),
        ),
    ]
