# Generated by Django 3.2.7 on 2022-08-06 18:34

import apps.interfaces.can_collection
import apps.interfaces.can_comment
import apps.interfaces.can_share
import apps.interfaces.can_thumbup
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artwork', '0001_initial'),
        ('business', '0006_tasklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='数据创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='数据失效时间')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=32, verbose_name='价格')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.art', verbose_name='艺术品')),
                ('tags', models.ManyToManyField(to='business.Tag', verbose_name='标签')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.interfaces.can_share.CanShare, apps.interfaces.can_collection.CanCollection, apps.interfaces.can_thumbup.CanThumbUp, apps.interfaces.can_comment.CanComment),
            managers=[
                ('logic_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
